---
layout: post
title:  "PHP exception handling"
date:   2017-10-10 15:01:00 +1000
categories: Geek
---

When I used `try catch` exception handling at work, I had the following questions:

- How does the key word `finally` works?

- When we use nested `catch`, could the one in child suppress the parent/consumer?

- Why there are more than one `catch` in the same `try` code block?

So I created this [code playground](https://code.sololearn.com/w7CDMXDlwCz3/#php) for experiments.